about/urls.py
from django.urls import path
from . import views

app_name="about"
urlpatterns = [
    path('about',views.about,name="about"),
    path('about_ar',views.about_ar,name="about_ar")
]

account/urls.py
from django.urls import path
from . import views
app_name="account"
urlpatterns = [
    path('login',views.log_in,name="login"),
    path('logout',views.log_out,name="logout"),
    path('signin',views.sign_in,name="signin"),
    #ar
    path('login_ar',views.log_in_ar,name="login_ar"),
    path('logout_ar',views.log_out_ar,name="logout_ar"),
    path('signin_ar',views.sign_in_ar,name="signin_ar"),
]

blog/urls.py
from django.urls import path
from . import views
app_name="blog"
urlpatterns = [
    path('blog',views.blog,name="blog"),
    path('blogdetails<int:id>',views.blogdetails,name="blogdetails"),
    path('addblog',views.addblog,name="addblog"),
    #ar
    path('blog_ar',views.blog_ar,name="blog_ar"),
    path('blogdetails_ar<int:id>',views.blogdetails_ar,name="blogdetails_ar"),
    path('addblog_ar',views.addblog_ar,name="addblog_ar"),
    
]

contact/urls.py
from django.urls import path
from . import views
app_name="contact"
urlpatterns = [
    path('contact',views.contact,name="contact"),
    path('contact_ar',views.contact_ar,name="contact_ar")
]

home/urls.py
from django.urls import path
from . import views
app_name="home"
urlpatterns = [
    path('',views.home,name="home"),
    path('home_ar',views.home_ar,name="home_ar"),
]

plants/urls.py
from django.urls import path
from . import views
app_name="plants"
urlpatterns = [
    path('plants',views.plants,name="plants"),
    path('plantdetials<int:id>',views.plantdetails,name="plantdetials"),
    path('card<int:id>',views.card,name="card"),
    path('pay',views.pay,name="pay"),
     #ar
    path('plants_ar',views.plants_ar,name="plants_ar"),
    path('plantdetials_ar<int:id>',views.plantdetails_ar,name="plantdetials_ar"),
    path('card_ar<int:id>',views.card_ar,name="card_ar"),
    path('pay_ar',views.pay_ar,name="pay_ar"),             
    
]

portfolio/urls.py
from django.urls import path
from . import views
app_name="portfolio"
urlpatterns = [
    path('portfolio',views.portfolio,name="portfolio"),
    path('portfolio_ar',views.portfolio_ar,name="portfolio_ar")
]

about/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models

# import user
from django.contrib.auth.models import User
# Create your models here.

class Blog(models.Model):
    # user relation
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    body = models.TextField()
    image = models.ImageField(upload_to='static/images')
    # date field current time
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title



# comment
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment

contact/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=122)
    email = models.CharField(max_length=122)
    subject = models.CharField(max_length=122)
    message = models.TextField()
    def __str__(self):
        return self.name

plants/models.py
from django.db import models

# Create your models here.
Water = [
        ('Succulents and cacti', 'Succulents and cacti'),
        ('Drought tolerant plants', 'Drought-tolerant plants'),
        ('Moisture loving plants', 'Moisture-loving plants'),
    ]
Sun = [
        ('Full sun plants', 'Full sun plants'),
        ('Partial sun partial shade plants', 'Partial sun/partial shade plants'),
        ('Shade loving plants', 'Shade-loving plants'),
    ]
Soil = [
        ('Neutral soil plants', 'Neutral soil plants'),
        ('Alkaline soil plants', 'Alkaline soil plants'),
        ('Acidic soil plants', 'Acidic soil plants'),
    ]
leaf_type = [
        ('Flat leaves', 'Flat leaves'),
        ('Curly leaves', 'Curly leaves'),
        ('Serrated leaves', 'Serrated leaves'),
        ('Semi circular leaves', 'Semi-circular leaves'),
        ('Triangular leaves', 'Triangular leaves'),
        ('Variegated leaves', 'Variegated leaves'),
        ('Tree leaves', 'Tree leaves'),
        ('Dark green leaves', 'Dark green leaves'),
        ('Ascending leaves', 'Ascending leaves'),
        ('Circular leaves', 'Circular leaves'),
    ]



class Plants(models.Model):
    scientific_name  = models.CharField(max_length=200)
    home  = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    price = models.IntegerField()
    description = models.TextField()
    water = models.CharField(max_length=200, choices=Water)
    sun = models.CharField(max_length=200, choices=Sun)
    soil = models.CharField(max_length=200, choices=Soil)
    leaf_type = models.CharField(max_length=200, choices=leaf_type)
    image = models.ImageField(upload_to='static/images')


    def __str__(self):
        return self.scientific_name

portfolio/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

class Portfolio(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='static/images')
    def __str__(self):
        return self.title

about/views.py
from django.shortcuts import render

# Create your views here.

def about(request):
    return render(request,'about.html')
def about_ar(request):
    return render(request,'about-ar.html')

blog/views.py
from django.shortcuts import render
# imoprt blog , cooment
from .models import Blog, Comment
# import user
from django.contrib.auth.models import User
# import pagenator
from django.core.paginator import Paginator
# import redirct
from django.shortcuts import redirect

import re
# Create your views here.

def blog(request):
   # blog def
    blog = Blog.objects.filter(title__regex=r'[A-Za-z]+')
    paginator = Paginator(blog, 8) # Show 8 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'blogs': page_obj}
    return render(request, 'blog.html',context)

def addblog(request):
    # add blog
    if request.method == 'POST':
        title = request.POST['title']
        body = request.POST['body']
        image = request.FILES['image']
        user = User.objects.get(id=request.user.id)
        blog = Blog(user=user, title=title, body=body, image=image)
        blog.save()
        return redirect('blog')
    return render(request, 'addblog.html')

def blogdetails(request,id):
    #single blog 
    id=id
    blog = Blog.objects.get(id=id)
    # comment
    comment = Comment.objects.filter(blog=blog)
    context = {'blog': blog, 'comments': comment}
    if request.method == 'POST':
        comment = request.POST['comment']
        user = User.objects.get(id=request.user.id)
        blog = Blog.objects.get(id=id)
        comment = Comment(user=user, blog=blog, comment=comment)
        comment.save()
        return redirect('blog:blogdetails', id)
    return render(request, 'single-post.html', context)


#ar
def blog_ar(request):
    # blog def
     blog = Blog.objects.filter(title__regex=r'[\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF]+')
     paginator = Paginator(blog, 8) # Show 8 contacts per page.
     page_number = request.GET.get('page')
     page_obj = paginator.get_page(page_number)
     context = {'blogs': page_obj}
     return render(request, 'blog-ar.html',context)
 
def addblog_ar(request):
        # add blog
        if request.method == 'POST':
            title = request.POST['title']
            body = request.POST['body']
            image = request.FILES['image']
            user = User.objects.get(id=request.user.id)
            blog = Blog(user=user, title=title, body=body, image=image)
            blog.save()
            return redirect('blog_ar')
        return render(request, 'addblog-ar.html')


def blogdetails_ar(request,id):
    #single blog 
    id=id
    blog = Blog.objects.get(id=id)
    # comment
    comment = Comment.objects.filter(blog=blog)
    context = {'blog': blog, 'comments': comment}
    if request.method == 'POST':
        comment = request.POST['comment']
        user = User.objects.get(id=request.user.id)
        blog = Blog.objects.get(id=id)
        comment = Comment(user=user, blog=blog, comment=comment)
        comment.save()
        return redirect('blog:blogdetails_ar', id)
    return render(request, 'single-post-ar.html', context)
        
        
        
        
        
        
def contains_arabic(text):
    arabic_pattern = re.compile(r'[\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF]+') # Matches Arabic Unicode characters
    return arabic_pattern.search(text) is not None

def contains_english(text):
    english_pattern = re.compile(r'[A-Za-z]+') # Matches English letters
    return english_pattern.search(text) is not None

contact/views.py
from django.shortcuts import render
# import contact
from .models import Contact
# import messages
from django.contrib import messages
# Create your views here.

def contact(request):
    if request.method == "POST":
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']
        contact = Contact(name=name, email=email, subject=subject, message=message)
        contact.save()
        messages.success(request, 'تم ارسال الرساله بنجاح')
    return render(request,'contact.html')

def contact_ar(request):
    if request.method == "POST":
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']
        contact = Contact(name=name, email=email, subject=subject, message=message)
        contact.save()
        messages.success(request, 'تم ارسال الرساله بنجاح')
    return render(request,'contact-ar.html')

plants/views.py
from django.shortcuts import render
from .models import Plants
# import paginator
from django.core.paginator import Paginator

# Create your views here.

def plants(request):
    #get all the categories
    plants = Plants.objects.filter(title__regex=r'[A-Za-z]+')
    #paginator
    paginator = Paginator(plants, 8) # Show 8 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    #create a dictionary
    context = {'plants':page_obj}
    return render(request,'plants.html',context)

def plantdetails(request,id):
    #single plant
    plant = Plants.objects.get(id=id)
    context = {'plant':plant}
    return render(request,'plantsdetails.html',context)

def card(request,id):
    #single plant
    plant = Plants.objects.get(id=id)
    context = {'plant':plant}
    return render(request,'cart.html',context)


def pay(request):
    #get id from url query string
    id = request.GET['id']
    #get count from query string in url
    count = request.GET['count']
    #get plant
    plant = Plants.objects.get(id=id)
    #get total price
    total = plant.price * int(count)
    #create a dictionary
    context = {'plant':plant,'count':count,'total':total}
    return render(request,'checkout.html',context)


#ar

def plants_ar(request):
    #get all the categories
    plants = Plants.objects.filter(title__regex=r'[\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF]+')
    #paginator
    paginator = Paginator(plants, 8) # Show 8 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    #create a dictionary
    context = {'plants':page_obj}
    return render(request,'plants-ar.html',context)


def plantdetails_ar(request,id):
    #single plant
    plant = Plants.objects.get(id=id)
    context = {'plant':plant}
    return render(request,'plantsdetails-ar.html',context)

def card_ar(request,id):
    #single plant
    plant = Plants.objects.get(id=id)
    context = {'plant':plant}
    return render(request,'cart-ar.html',context)


def pay_ar(request):
    #get id from url query string
    id = request.GET['id']
    #get count from query string in url
    count = request.GET['count']
    #get plant
    plant = Plants.objects.get(id=id)
    #get total price
    total = plant.price * int(count)
    #create a dictionary
    context = {'plant':plant,'count':count,'total':total}
    return render(request,'checkout-ar.html',context)

portfolio/views.py
from django.shortcuts import render
#import portfolio and category
from .models import Portfolio, Category


# Create your views here.

def portfolio(request):
    #get all the categories
    categories = Category.objects.all()
    #get all the portfolios
    portfolios = Portfolio.objects.all()
    #create a dictionary
    context = {'category':categories,'portfolio':portfolios}
    return render(request,'portfolio.html',context)

#ar
def portfolio_ar(request):
    #get all the categories
    categories = Category.objects.all()
    #get all the portfolios
    portfolios = Portfolio.objects.all()
    #create a dictionary
    context = {'category':categories,'portfolio':portfolios}
    return render(request,'portfolio-ar.html',context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en ">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title -->
    <title>Plants</title>

    <!-- Favicon -->
    <link rel="icon" href="{% static 'img/core-img/favicon.ico' %}">

    <!-- Core Stylesheet -->
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>

<body >
    <!-- Preloader -->
    <div class="preloader d-flex align-items-center justify-content-center">
        <div class="preloader-circle"></div>
        <div class="preloader-img">
            <img src="{% static 'img/core-img/leaf.png' %}" alt="">
        </div>
    </div>

    <!-- ##### Header Area Start ##### -->
    <header class="header-area">

        <!-- ***** Top Header Area ***** -->
        <div class="top-header-area">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="top-header-content d-flex align-items-center justify-content-between">
                            <!-- Top Header Content -->
                            <div class="top-header-meta">
                                <a href="#" data-toggle="tooltip" data-placement="bottom" title="infodeercreative@gmail.com"><i class="fa fa-envelope-o" aria-hidden="true"></i> <span>Email: info@gmail.com</span></a>
                                <a href="#" data-toggle="tooltip" data-placement="bottom" title="+1 234 122 122"><i class="fa fa-phone" aria-hidden="true"></i> <span>Call Us: +1 234 122 122</span></a>
                            </div>

                            <!-- Top Header Content -->
                            <div class="top-header-meta d-flex">
                                <!-- Language Dropdown -->
                                <div class="language-dropdown">
                                    <div class="dropdown">
                                        <button class="btn btn-secondary dropdown-toggle mr-30" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Language</button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                            <a class="dropdown-item" href="{% url 'home:home' %}">ENGLISH</a>
                                            <a class="dropdown-item" href="{% url 'home:home_ar' %}">ARABIC</a>
                                        </div>
                                    </div>
                                </div>
                                <!-- Login -->
                                <div class="login">
                                    <!-- chech if login or not -->
                                    {% if user.is_authenticated %}
                                    <!--check if super user-->
                                    {% if user.is_superuser %}
                                    <a href="{% url 'admin:index' %}"><i class="fa fa-user" aria-hidden="true"></i> <span>Dashboard</span></a>
                                    {% endif %}
                                    <a href="{% url 'account:logout' %}"><i class="fa fa-user" aria-hidden="true"></i> <span>logout</span></a>
                                    {% else %}
                                    <a href="{% url 'account:login' %}"><i class="fa fa-user" aria-hidden="true"></i> <span>Login</span></a>
                                    <a href="{% url 'account:signin' %}"><i class="fa fa-user" aria-hidden="true"></i> <span>register</span></a>
                                    {% endif %}
                                </div>
                                <!-- Cart -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- ***** Navbar Area ***** -->
        <div class="alazea-main-menu">
            <div class="classy-nav-container breakpoint-off">
                <div class="container">
                    <!-- Menu -->
                    <nav class="classy-navbar justify-content-between" id="alazeaNav">

                        <!-- Nav Brand -->
                        <a href="{% url 'home:home' %}" class="nav-brand"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>

                        <!-- Navbar Toggler -->
                        <div class="classy-navbar-toggler">
                            <span class="navbarToggler"><span></span><span></span><span></span></span>
                        </div>

                        <!-- Menu -->
                        <div class="classy-menu">

                            <!-- Close Button -->
                            <div class="classycloseIcon">
                                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                            </div>

                            <!-- Navbar Start -->
                            <div class="classynav">
                                <ul>
                                    <li><a href="{% url 'home:home' %}">Home</a></li>
                                    <li><a href="{% url 'about:about' %}">About</a></li>
                                    <li><a href="{% url 'blog:blog' %}">blogs</a></li>
                                    <li><a href="{% url 'plants:plants' %}">Plants</a></li>
                                    <li><a href="{% url 'portfolio:portfolio' %}">Portfolio</a></li>
                                    <li><a href="{% url 'contact:contact' %}">Contact</a></li>
                                </ul>
                            </div>
                            <!-- Navbar End -->
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ##### Header Area End ##### -->

    {% block body %}


    {% endblock %} 

    
    <!-- ##### Footer Area Start ##### -->
    <footer class="footer-area bg-img" style="background-image: url({% static 'img/bg-img/3.jpg' %});">
        <!-- Main Footer Area -->
        <div class="main-footer-area">
            <div class="container">
                <div class="row">

                    <!-- Single Footer Widget -->
                    <div class="col-12 col-sm-6 col-lg-4">
                        <div class="single-footer-widget">
                            <div class="footer-logo mb-30">
                                <a href="{% url 'home:home' %}"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
                            </div>
                            <p>here you will found all plants and flower that you want</p>
                            <div class="social-info">
                                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    </div>

                    <!-- Single Footer Widget -->
                    <div class="col-12 col-sm-6 col-lg-4">
                        <div class="single-footer-widget">
                            <div class="widget-title">
                                <h5>QUICK LINK</h5>
                            </div>
                            <nav class="widget-nav">
                                <ul>
                                    <li><a href="{% url 'home:home' %}">home</a></li>
                                    <li><a href="{% url 'about:about' %}">about</a></li>
                                    <li><a href="{% url 'plants:plants' %}">Plants</a></li>
                                    <li><a href="{% url 'blog:blog' %}">blog</a></li>
                                    <li><a href="{% url 'portfolio:portfolio' %}">galary</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>

                    <!-- Single Footer Widget -->
                    <div class="col-12 col-sm-6 col-lg-4">
                        <div class="single-footer-widget">
                            <div class="widget-title">
                                <h5>CONTACT</h5>
                            </div>

                            <div class="contact-information">
                                <p><span>Address:</span> 505 Mansoura</p>
                                <p><span>Phone:</span> +2 122 122 122</p>
                                <p><span>Email:</span> info.deercreative@gmail.com</p>
                                <p><span>Open hours:</span> Mon - Sun: 8 AM to 9 PM</p>
                                <p><span>Happy hours:</span> Sat: 2 PM to 4 PM</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ##### Footer Area End ##### -->

    <!-- ##### All Javascript Files ##### -->
    <!-- jQuery-2.2.4 js -->
    <script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'js/bootstrap/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    <!-- All Plugins js -->
    <script src="{% static 'js/plugins/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'js/active.js' %}"></script>
</body>

</html>

templates/single-post-ar.html
{% extends 'base-ar.html' %}
{% load static %}
{% block body %}
    <!-- ##### Breadcrumb Area Start ##### -->
    <div class="breadcrumb-area">
        <!-- Top Breadcrumb Area -->
        <div class="top-breadcrumb-area bg-img bg-overlay d-flex align-items-center justify-content-center" style="background-image: url({% static 'img/bg-img/24.jpg' %});">
            <h2>تفاصيل المقالة</h2>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'home:home_ar' %}"><i class="fa fa-home"></i> الصفحة الرئيسية</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'blog:blog_ar' %}">المقالات</a></li>
                            <li class="breadcrumb-item active" aria-current="page">بيانات المقالة</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Breadcrumb Area End ##### -->
    <!-- ##### Blog Content Area Start ##### -->
    <section class="blog-content-area section-padding-0-100">
        <div class="container">
            <div class="row justify-content-center">
                <!-- Blog Posts Area -->
                <div class="col-12 col-md-12">
                    <div class="blog-posts-area">
                        <!-- Post Details Area -->
                        <div class="single-post-details-area">
                            <div class="post-content">
                                <h4 class="post-title">{{blog.title}}</h4>
                                <div class="post-meta mb-30">
                                    <a href="#"><i class="fa fa-clock-o" aria-hidden="true"></i> {{blog.date}}</a>
                                    <a href="#"><i class="fa fa-user" aria-hidden="true"></i>{{blog.user}}</a>
                                </div>
                                <div class="post-thumbnail mb-30 w-100">
                                    <img src="{{blog.image.url}}" class="w-100" alt="">
                                </div>
                                <p>{{blog.body}}</p>
                        </div>
                        <!-- Post Tags & Share -->
                        <div class="post-tags-share d-flex justify-content-between align-items-center">
                            <!-- Share -->
                            <div class="post-share">
                                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                            </div>
                        </div>
                        <!-- comment area-->
                        <div class="comment_area">
                            <h5 class="title">التعليقات</h5>
                            <ol>
                                <!-- Single Comment Area -->
                                {% if comments %}
                                {% for comment in comments %}
                                <!-- Single Comment Area -->
                                <li class="">
                                    <!-- Comment Content -->
                                    <div class="ml-4">
                                        <!-- Comment Author -->
                                    
                                        <!-- Comment Meta -->
                                        <div class="comment-meta">
                                            <a href="#" class="m2 mr-4"><i class="fa fa-user"></i> {{comment.user}}</a>

                                            <!--date field with clock icon-->
                                            <a href="#" class="post-date m2"><i class="fa fa-clock-o"></i> {{comment.date}}</a>
                                            <p class="ml-4">{{comment.comment}}</p>
                                        </div>
                                    </div>
                                </li>
                                {% endfor %}
                                {% else %}
                                <p>لا يوجد تعليقات بعد</p>
                                {% endif %}
                            </ol>
                        </div>
                            

                        <!-- Leave A Comment -->
                        <div class="leave-comment-area clearfix">
                            <div class="comment-form">
                                <h4 class="headline">اترك تعليق</h4>
                                <div class="contact-form-area">
                                    <!-- Comment Form -->
                                    <form action="" method="post">
                            
                                        {% csrf_token %}
                                        <div class="row">
                                            <!-- add hidden input value is blog id-->
                                            <input type="hidden" name="id" value="{{blog.id}}">
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <textarea class="form-control" name="comment" id="message" cols="30" rows="10" placeholder="Comment" required></textarea>
                                                </div>
                                            </div>
                                            <!--check is login or not-->
                                            {% if user.is_authenticated %}
                                            <div class="col-12">
                                                <button type="submit" class="btn alazea-btn">ارسال</button>
                                            </div>
                                            {% else %}
                                            <div class="col-12">
                                                <a href="{% url 'account:login_ar' %}" class="btn alazea-btn" > تسجيل الدخول اولا </a>
                                            </div>
                                            {% endif %}
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Blog Content Area End ##### -->
    {% endblock %}